<?php
$labels['vacationmessagealert'] = 'You currently have a vacation message set';
$labels['change'] = 'Change';
$labels['vacationmessage'] = 'Vacation Message';
$labels['changepassword'] = 'Change Password';
$labels['autoresponderenabled'] = 'Auto-responder enabled';
$labels['subject'] = 'Subject';
$labels['message'] = 'Message';
$labels['oldpassword'] = 'Old Password';
$labels['newpassword'] = 'New Password';
$labels['newpassword2'] = 'New Password (again)';
$labels['oldpasswordnotcorrect'] = 'Old password was not correct!';
$labels['newpassnotmatch'] = 'New passwords did not match!';
$labels['newpasstooshort'] = 'New password is too short';
$labels['itmustbeatleast'] = 'It must be at least';
$labels['characterslong'] = 'characters long';
$labels['invalidpassword'] = 'Invalid password, please try a more complex one.';
$labels['couldnotchange'] = 'Password could not be changed.';
$labels['erroruserdomainparts'] = 'Unable to locate user/domain parts in';
$labels['unabletologinqmailadmin'] = 'Unable to login to qmailadmin';
$labels['unabletofindmodityform'] = 'Unable to find modify user form';
$labels['cantconnect'] = 'Could not open a connection to';
$labels['cantreadfrom'] = 'Could not read data from';
?>