<?php
$labels['vacationmessagealert'] = 'Você possui uma mensagem de férias ativa';
$labels['change'] = 'Configurar';
$labels['vacationmessage'] = 'Mensagem de Férias';
$labels['changepassword'] = 'Trocar Senha';
$labels['autoresponderenabled'] = 'Ativar a mensagem de férias';
$labels['subject'] = 'Assunto';
$labels['message'] = 'Mensagem';
$labels['oldpassword'] = 'Senha atual';
$labels['newpassword'] = 'Nova senha';
$labels['newpassword2'] = 'Confirmação da nova senha';
$labels['oldpasswordnotcorrect'] = 'A senha atual está incorreta!';
$labels['newpassnotmatch'] = 'As novas senhas são diferentes!';
$labels['newpasstooshort'] = 'A nova senha é muito curta';
$labels['itmustbeatleast'] = 'Ela deve conter mais do que ';
$labels['characterslong'] = 'caracteres';
$labels['invalidpassword'] = 'Senha inválida. Tente utilizar uma senha mais complexa.';
$labels['couldnotchange'] = 'A senha não pode ser alterada.';
$labels['erroruserdomainparts'] = 'Não foi possível localizar o e-mail e/ou domínio em';
$labels['unabletologinqmailadmin'] = 'Não foi possível fazer login no serviço de troca de senhas';
$labels['unabletofindmodityform'] = 'Não foi possível se conectar ao serviço de troca de senhas';
$labels['cantconnect'] = 'Não foi possível se conectar a';
$labels['cantreadfrom'] = 'Não foi possível obter dados de';
?>